language: python
python:
  - 3.6.1
addons:
  code_climate:
    repo_token: 636d864c406e72477270e98914162c1a5b9603412bc1eed5d7588762f4692f84
  codacy:
    repo_token: 4e98d2d730c441c181ca6633872b2317
install:
#  - cp contrib/env-sample .env
  - pip install -q -r requirements-dev.txt
# before_script:

script:
  - flake8 .
  - pytest --cov=core
after_success:
  - codecov
#notifications:
#  slack:
#    secure:
