language: python
python:
  - 3.6.1
install:
#  - cp contrib/env-sample .env
  - pip install -q -r requirements-dev.txt
# before_script:

script:
  - flake8 .
  - pytest
after_success:
  - codecov
#notifications:
#  slack:
#    secure:
